name: Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-and-test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci
      - name: Check formatting
        run: npm run check:format
      - name: Check
        id: check
        run: npm run check
        if: ${{ !cancelled() }}
