name: Pipeline
permissions: write-all

on:
  workflow_dispatch:
  push:

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml

  build:
    name: Build
    needs: check
    uses: ./.github/workflows/build.yml
